### ISSUE TITLE
Fix dependancies for Getting Started documentation

### ISSUE THREAD

**Issue by rosesopranodesertbat** [hicommonwealth/edgeware-homepage#10]
On this page: https://edgewa.re/lockdrop/gettingstarted.html there appears to be a number of dependancies that are missing from the documentation to compile and install subkey. https://github.com/paritytech/substrate#61-hacking-on-substrate has the full list.

**Comment by thomivy** [comment]
I've added a note to the documentation while we determine if there is a minimal transfer of the content from your linked page, or if we need to basically copy it all in for the use of Subkey : )

**Comment by drewstone** [comment]
@carumusan This may have been due to previous steps being outdated, but in the first line we have addressed the same steps if the ones described do fail. 

> If these steps fail, you may need to install other dependencies for Subkey.

Ideally, you will need to click the link in the first step and this leads you to the steps described in the substrate readme.

If you are downloading rustup for the first time as we also link, there are some instructions in the installer that you will need to follow. This should be understood when it prompts you to do so such as `source $HOME/.cargo/env`.
